# Generated by Django 4.2.5 on 2023-10-06 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0001_initial'),
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='materia',
        ),
        migrations.AddField(
            model_name='profesor',
            name='materia_id',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, to='materia.materia'),
            preserve_default='True',
        ),
    ]
