# Generated by Django 4.2.5 on 2023-10-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={},
        ),
    ]
