# Generated by Django 4.2.5 on 2023-10-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='año',
            field=models.IntegerField(blank='true', default='1', null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='alumno',
            name='nivel',
            field=models.CharField(blank='true', max_length=10, null='True'),
            preserve_default='True',
        ),
    ]
